FROM python:3.11-slim

WORKDIR /app
COPY . /app

# Install all required packages including python-multipart
RUN pip install fastapi uvicorn \
    python-jose \
    python-multipart \
    passlib[bcrypt] \
    kubernetes

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

