apiVersion: v1
kind: Service
metadata:
  name: lab-backend-external
  namespace: devops-labs
spec:
  type: NodePort
  selector:
    app: lab-backend
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
