
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-backend
  namespace: devops-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-backend
  template:
    metadata:
      labels:
        app: lab-backend
    spec:
      serviceAccountName: lab-manager
      containers:
      - name: backend
        image: syednadeembe/lab-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: lab-backend
  namespace: devops-labs
spec:
  selector:
    app: lab-backend
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-labs
data:
  LAB_IMAGE: syednadeem/ttyd-lab:latest
  DOMAIN: 13.233.148.15.nip.io
  NAMESPACE_PREFIX: lab-
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devops-labs
type: Opaque
data:
  JWT_SECRET_KEY: c3VwZXJzZWNyZXRrZXk=  # base64 of 'supersecretkey'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-manager
  namespace: devops-labs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lab-manager-binding
subjects:
- kind: ServiceAccount
  name: lab-manager
  namespace: devops-labs
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

