apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-ui
  namespace: devops-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-ui
  template:
    metadata:
      labels:
        app: lab-ui
    spec:
      containers:
      - name: nginx
        image: syednadeembe/lab-ui:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab-ui
  namespace: devops-labs
spec:
  type: NodePort
  selector:
    app: lab-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
