apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lab-cleanup-binding
subjects:
- kind: ServiceAccount
  name: lab-cleanup
  namespace: devops-labs
roleRef:
  kind: ClusterRole
  name: lab-cleanup-role
  apiGroup: rbac.authorization.k8s.io

