apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: devops-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session
        image: syednadeembe/lab-session-service:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: devops-labs
spec:
  type: NodePort
  selector:
    app: session-service
  ports:
  - port: 80
    targetPort: 8001
    nodePort: 30081

