# rbac-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-restricted-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: devops-labs
roleRef:
  kind: ClusterRole
  name: pod-reader-restricted
  apiGroup: rbac.authorization.k8s.io

